[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
evm_version = "cancun"

fs_permissions = []

remappings = [
  "@contracts-bedrock/=lib/optimism/packages/contracts-bedrock/src/",
  "@contracts-bedrock-interfaces/=lib/optimism/packages/contracts-bedrock/interfaces/",
  "@solady-v0.0.245/=lib/optimism/packages/contracts-bedrock/lib/solady-v0.0.245/src/",
  "@solady/=lib/optimism/packages/contracts-bedrock/lib/solady/src/",
  "@openzeppelin/contracts=lib/optimism/packages/contracts-bedrock/lib/openzeppelin-contracts/contracts"
]

[rpc_endpoints]
opchain_a = "http://localhost:9545"
opchain_b = "http://localhost:9546"
opchain_c = "http://localhost:9547"
